config:
  info: "admin gateway config info dev (branch develop)"

spring:
  redis:
    host: localhost
    port: 6379
  #  password: KV&O0v#J
    database: 15 # 默认库
    lettuce: # jedis/lettuce
      pool:
        max-active: 80 # 最大活跃链接数 默认8
        max-idle: 80 # 最大空闲连接数 默认8
        min-idle: 0 # 最小空闲连接数 默认0
        max-wait: -1ms
  datasource:
    url: jdbc:mysql://localhost:3306/coin?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
