config:
  info: "admin gateway config info dev (branch develop)"

spring:
  redis:
    host: localhost
    port: 6379
  #  password: KV&O0v#J
    database: 15 
    lettuce: # jedis/lettuce
      pool:
        max-active: 80
        max-idle: 80 
        min-idle: 0 
        max-wait: -1ms
  datasource:
    url: jdbc:mysql://localhost:3306/coin?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
